server:
  port: 8080 # Default to 8080 if not set

spring:
  datasource:
    url: jdbc:postgresql://localhost:3000/barber_token_db
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: dev.madhurendra@gmail.com
    password: smyh tuia uwfo titv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: 3xAmPl3SeCuR3KeYth@t_iS_AtLeAst32Ch@rs
  expiration: 3600000
