name: SonarCloud Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - ".github/workflows/backendSonar.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "backend/**"

jobs:
  backend-sonar-analysis:
    if: >
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' &&
      startsWith(github.head_ref, 'BE_') &&
      github.event.pull_request.merged == false)
    name: BE BarberPRO Services Sonar Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze with SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.BARBER_PRO_SONAR_TOKEN }}
        run: >
          mvn -B clean verify
          sonar:sonar
          -Dsonar.projectKey=dev-madhurendra_BarberPRO
          -Dsonar.organization=your_org_name
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=${{ secrets.BARBER_PRO_SONAR_TOKEN }}
