name: Simple CI

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'frontend/**'
  pull_request:
    branches: [main]
    paths:
      - 'backend/**'
      - 'frontend/**'

jobs:
  build-backend:
    name: 🚀 Build Spring Boot Backend (Java 21)
    if: contains(github.event.head_commit.message, '[backend]') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 🛠️ Build with Maven
        run: |
          cd backend
          mvn clean install -DskipTests

  build-frontend:
    name: 🌐 Build React Frontend
    if: contains(github.event.head_commit.message, '[frontend]') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install and Build
        run: |
          cd frontend
          npm install
          npm run build
